# Generated by Django 4.0.9 on 2023-04-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('location', models.CharField(max_length=100, verbose_name='محل')),
            ],
            options={
                'verbose_name': 'مراسم',
                'verbose_name_plural': 'مراسم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ceremony.ceremony', verbose_name='مراسم')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت کننده',
                'verbose_name_plural': 'شرکت کنندگان',
            },
        ),
    ]
