# Generated by Django 4.0.9 on 2023-04-10 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='سوال')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': '1. نظرسنجی ها',
                'ordering': ('-create',),
            },
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30, verbose_name='گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_option', to='poll.poll', verbose_name='برای نظرسنجی')),
                ('voters', models.ManyToManyField(blank=True, to='accounts.user', verbose_name='رای دهندگان')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': '2. گزینه ها',
            },
        ),
    ]
